{% set name = "FreeFem" %}
{% set version = "4.12" %}
{% set sha256 = "291c5f46761711d6303914f9c4f165fd85a7b7b69141f7473e0b6484ce6ab0f5" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-sources/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [py2k or osx or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - bison
    - cmake
    - flex
    - m4
    - make
    - patch
    - unzip
  host:
    - arpack
    - gmm
    - hdf5
    - libopenblas
    - suitesparse
    - superlu
    - tetgen

about:
  home: https://freefem.org/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'FreeFem : A high level multiphysics finite element software'
  description: >
    FreeFEM is a popular 2D and 3D partial differential equations (PDE) solver used by thousands of researchers across the world. It allows you to easily implement your own physics modules using the provided FreeFEM language. FreeFEM offers a large list of finite elements, like the Lagrange, Taylor-Hood, etc., usable in
    the continuous and discontinuous Galerkin method framework.
  doc_url: https://doc.freefem.org
  dev_url: https://github.com/FreeFem

extra:
  recipe-maintainers:
    - ldallolio
    - cnrdn
    - fbordeu
