{% set name = "FreeFem" %}
{% set version = "4.13" %}
{% set sha256 = "d296adc42c6b0cc5f148c44b00bea15939d6c0dbe391613dea8a0693c2c0e3b7" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-sources/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - Makefile.am_conda.patch
    - Makefile.am_src_bin-win32_conda.patch

build:
  number: {{ build }}
  skip: true  # [py2ks]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]    
    - autoconf  # [unix]
    - m2-autoconf  # [win]
    - m2-automake-wrapper  # [win]
    - automake  # [unix]
    - bison  # [unix]
    - m2-bison  # [win]
    - flex  # [unix]
    - m2-flex  # [win]
    - m4  # [unix]
    - m2-m4  # [win]
    - make  # [unix]
    - patch  # [unix]
    - m2-patch  # [win]
    - m2w64-make  # [win]
    - m2-base  # [win]    
    - unzip  # [unix]
    - m2-unzip  # [win]
  host:
    - arpack
    - gmm  # [unix]
    - hdf5
    - libopenblas
    - suitesparse
    - superlu  # [unix]
    - tetgen
    - zlib

test:
  commands:
    - test -f $PREFIX/bin/FreeFem++  # [unix]
    - if not exist $PREFIX\\bin\\FreeFem++ exit 1  # [win]    
    - test -f $PREFIX/bin/FreeFem++-nw  # [unix]
    - if not exist $PREFIX\\bin\\FreeFem++-nw exit 1  # [win] 
    - test -f $PREFIX/bin/ff-c++  # [unix]
    - if not exist $PREFIX\\bin\\ff-c++ exit 1  # [win] 
    - test -f $PREFIX/bin/ff-get-dep  # [unix]
    - if not exist $PREFIX\\bin\\ff-get-dep exit 1  # [win]
    - test -f $PREFIX/bin/ff-pkg-download  # [unix
    - if not exist $PREFIX\\bin\\ff-pkg-download exit 1  # [win]
    - FreeFem++ $PREFIX/share/FreeFEM/${PKG_VERSION}/examples/tutorial/beam.edp  # [linux]

about:
  home: https://freefem.org/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'FreeFem : A high level multiphysics finite element software'
  description: >
    FreeFEM is a popular 2D and 3D partial differential equations (PDE) solver used by thousands of researchers across the world. It allows you to easily implement your own physics modules using the provided FreeFEM language. FreeFEM offers a large list of finite elements, like the Lagrange, Taylor-Hood, etc., usable in
    the continuous and discontinuous Galerkin method framework.
  doc_url: https://doc.freefem.org
  dev_url: https://github.com/FreeFem

extra:
  recipe-maintainers:
    - ldallolio
    - cnrdn
    - fbordeu
